# Generated by Django 3.1.3 on 2020-11-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=8, verbose_name='dating gender')),
                ('location', models.CharField(max_length=32, verbose_name='accepted city')),
                ('min_distance', models.IntegerField(default=1, verbose_name='min distance')),
                ('max_distance', models.IntegerField(default=10, verbose_name='max distance')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='min age of dating')),
                ('max_dating_age', models.IntegerField(default=45, verbose_name='max age of dating')),
                ('vibration', models.BooleanField(default=True, verbose_name='open vibe')),
                ('only_match', models.BooleanField(default=True, verbose_name='allowed check only matched')),
                ('auto_play', models.BooleanField(default=True, verbose_name='awak on play')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('birth_year', models.IntegerField(default=2000)),
                ('birth_month', models.IntegerField(default=1)),
                ('birth_day', models.IntegerField(default=1)),
                ('avatar', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=32)),
            ],
        ),
    ]
